### ISSUE TITLE
PiVPN Profiles gives "Loading the page failed. Please try again." error

### ISSUE THREAD

**Issue by yesrod** [mitchellurgero/openrsd#24]
When navigating to the PiVPN profiles section, an error is displayed that says "Loading the page failed. Please try again."

The following is contained in the lighttpd logs.

```
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught Error: Call to undefined function getDirContents() in /var/www/html/openrsd/pages/openvpn.php:33
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/html/openrsd/page.php(130): include()
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /var/www/html/openrsd/page.php(58): openvpn()
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr: #2 {main}
2018-06-14 12:24:37: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/html/openrsd/pages/openvpn.php on line 33
```

**Comment by yesrod** [comment]
Fixed by changing line 33 in ```pages/openvpn.php``` to

```
                    $log_files = OpenRSD::getDirContents('/home/'.$iuser.'/ovpns');
```

**Comment by mitchellurgero** [comment]
Good catch, the master branch has been updated.

**Comment by gnanet** [comment]
whohooo a new  something to sync my fork to :D
